Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -46,6 +46,4 @@ jobs:
      - name: Test run 3
        run: echo "$out1"
      - name: Test run 4
-       run: |
-          echo "Error!" 1>&2
-          exit 64
+       run: echo "Error!" 1>&2
